language: python
sudo: false

python:
  - '3.6'

install:
  - travis_retry pip install tox-travis

script:
  - tox -- -sv

deploy:
  provider: pypi
  user: chassing
  password:
    secure: in2DSK8c0lMGWC324zksClImfxJ3g6AC2Meu/5O0GbjnBemDahfgNwlCWoVoFKBeu2UoyVCOa2vOHkMAbuaUi0rci1YjnOqk6eG2i4iTZKAKx1r6stxnh6ocHbWY2VHNBfqw/KyRN3n5HeGwAcQWmIJL7sRr8kVI1GHd7nviZzU/dC+TQSZktiLWFS1smzfcGulgIpAER2rdg1LVAXn//+1XeXPu/Cd0QTNUw48UBeKEbkhGiTWpNKSkFxADVS12LIsWB4nHnHEQCRokI24x/WVyDxRcWF8sJED4Cf2TbAbqwhVPnEfBWYlRf3afM3EzZgbvQjBul5wcWSh60BjyckxfgYkVVcW3UadHi+ekOl7/tuyfPNLEM+5Y2DccZbpEHlChBhy63+JpURlzL1zimN63yFEwODO/jrONSJpcMGLy81zlI6T5WoURT5BGLZxacscLH+yOVyw9khUtd7bBNJK/3iiyF9gexiabpimU37ldBiFB0OW4G1tYwT/Y6CsetLpCrT/G5fGQ6rU7gCq3fyNgB+fX3N07yJUSVlUQQ0XwVataGOTdhHJFcLJVWv6uHnw1P35uiQIYzJbft3Yn/xHrzufBHtWATpkYVDy+uuKDj8pYDfZgTjDEdz9SC+/5KtavhZZT+29Fh5nG+kDIt4mMGqJVkHGjVyDWs25sqb4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: chassing/aionap
